config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#welcome'
  get 'samples/show'
  get 'samples/ajax'
  post 'samples/post_ajax'
  get 'components/show'
  get 'checkboxes/show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/checkboxes_controller.rb
class CheckboxesController < ApplicationController
  def show
  end
end

app/controllers/components_controller.rb
class ComponentsController < ApplicationController
  def show
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  def show
  end

  def ajax
    respond_to do |format|
      format.html # ajax.html.erb
      format.json { render json: { name: "ok" } }
    end
  end

  def post_ajax
    render json: {name: "piyopiyo"}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/checkboxes/show.html.erb
<h1>Checkbox</h1>

<div id="checkboxes_app" data-vue="checkbox_sample">
  <input id="checkbox1" v-on:click.prevent="checkbox1_clicked" type="checkbox" v-bind:checked="checkbox1" v-bind:disabled="ch1_disabled">
  <label for="checkbox1">{{ checkbox1 }}</label>

  <input id="checkbox2" type="checkbox" v-on:click.prevent="checkbox2_clicked" v-model="checkbox2">
  <label for="checkbox2">{{ checkbox2 }}</label>

  <input id="checkbox3" type="checkbox" v-on:click.prevent="checkbox3_clicked" v-model="checkbox3">
  <label for="checkbox3">{{ checkbox3 }}</label>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebpackerTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container" data-behavior="vue">
      <%= yield %>
    </div>
  <div>
    <br>
    <%= link_to "root", root_path %>
  </div>
  </body>
</html>

app/views/pages/welcome.html.erb
<h1>Pages#welcome</h1>

<div id="hello" data-vue="hello">
  {{ message }}
</div>

<ul>
  <ii><%= link_to 'samples', samples_show_path %></ii>
  <ii><%= link_to 'components', components_show_path %></ii>
  <ii><%= link_to 'checkboxes', checkboxes_show_path %></ii>
  <ii><%= link_to 'ajax', samples_ajax_path %></ii>
</ul>

app/views/samples/ajax.html.erb
<div data-vue="ajax">
  <form @submit.prevent="submitForm">
    <div>
      <label for="name">Name:</label><br>
      <input id="name" type="text" v-model="name"/>
    </div>

    <button type="submit">Submit</button>
    <div>
      <h3>Response from server:</h3>
      <pre>{{ response }}</pre>
    </div>
  </form>
</div>

app/views/samples/show.html.erb
<h1>Samples#show</h1>


<h2>binding</h2>
<div id="name_app" data-vue="name_app">
  <label for="name">Name:</label>
  <input id="name" type="text" v-model="name" /> <!--v-model is doing the magic here-->
  <p>{{ name }}</p>
</div>

<h2>lazy binding</h2>
<div id="name_lazy_app" data-vue="name_lazy_app">
  <label for="name">Name:</label>
  <input id="name" type="text" v-model.lazy="name" /> <!--v-model is doing the magic here-->
  <p>{{ name }}</p>
</div>

<h2>toggle color</h2>
<div id="toggle_app" data-vue="toggle_app">
  <button @click="active = !active" :aria-pressed="active ? 'true' : 'false'">Toggle me</button>
  <p :class="{ red: active }">Sometimes I need to be styled differently</p>
</div>

<h2>toggle panel</h2>
<div id="toggle_panel_app" data-vue="toggle_panel_app">
  <button @click="show = !show" :aria-expanded="show ? 'true' : 'false'">
    Toggle Panel
  </button>
  <p v-if="show">hello</p>
</div>

<h2>toggle with v-show</h2>
<!-- v-showを使うと宣言的になってtoggleの場合は非常によい -->
<div id="toggle_with_v_show" data-vue="toggle_with_v_show">
  <label for="textarea">What is your favorite kind of taco?</label>
  <br>
  <textarea id="textarea" v-model="tacos"></textarea>
  <br>
  <button v-show="tacos">Let us know!</button>
</div>

<h2>form</h2>
<div id="form_app" data-vue="form_app">
  <form @submit.prevent="submitForm">
    <div>
      <label for="name">Name:</label><br>
      <input id="name" type="text" v-model="name" required/>
    </div>
    <div>
      <label for="email">Email:</label><br>
      <input id="email" type="email" v-model="email" required/>
    </div>
    <div>
      <label for="caps">HOW DO I TURN OFF CAPS LOCK:</label><br>
      <textarea id="caps" v-model="caps" required></textarea>
    </div>
    <button :class="[name ? activeClass : '']" type="submit">Submit</button>
    <div>
      <h3>Response from server:</h3>
      <pre>{{ response }}</pre>
    </div>
  </form>
</div>